name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn add storybook -router -D
        run: yarn

      - name: Test coverage
        run: |
          yarn test

      - name: Validate test coverage
        run: |
          coverage=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          min_coverage=90
          if (( $(echo "$coverage < $min_coverage" | bc -l) )); then
            echo "O coverage de testes é $coverage e é inferior a $min_coverage%. Abortando o pull request."
            exit 1
          fi
