name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set SKIP_CYPRESS_INSTALL
        run: echo "SKIP_CYPRESS_INSTALL=true" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - run: |
          if [ "$SKIP_CYPRESS_INSTALL" != "true" ]; then
            yarn install
          fi
          
      - name: Test coverage
        run: |
          yarn test

      - name: Validate test coverage
        run: |
          coverage=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          min_coverage=90
          if (( $(echo "$coverage < $min_coverage" | bc -l) )); then
            echo "O coverage de testes é $coverage e é inferior a $min_coverage%. Abortando o pull request."
            exit 1
          fi
